penske-media-corp/pmc-larva

- packages/larva-patterns/modules/footer-menus/footer-menus.twig
- packages/larva/lib/writeData.js
> Support variant in JSON CLI command 

- packages/larva-tokens/build/artinamerica.custom-properties.css
- packages/larva-tokens/build/artinamerica.map.scss
- packages/larva-tokens/build/artnews.custom-properties.css
- packages/larva-tokens/build/artnews.map.scss
- packages/larva-tokens/build/default.custom-properties.css
- packages/larva-tokens/build/default.map.scss
- packages/larva-tokens/build/wwd.custom-properties.css
- packages/larva-tokens/build/wwd.map.scss
- packages/larva-tokens/src/base/aliases.json
- packages/larva-tokens/src/base/font-family.json
- packages/larva-tokens/src/brands/artinamerica.json
- packages/larva-tokens/src/brands/artnews.json
- packages/larva-tokens/style-guides/artinamerica.html
- packages/larva-tokens/style-guides/artnews.html
- packages/larva-tokens/style-guides/default.html
- packages/larva-tokens/style-guides/wwd.html
Also:
* Update webfont family names to match the font files for local viewing
* Add fallbacks to webfont stacks
> AMH Tokens - Better font-family fallbacks

- packages/larva-patterns/objects/o-figure/o-figure.prototype.js
- packages/larva-patterns/objects/o-tease/o-tease.prototype.js
* Use 1px transparent data URI for placeholder image
* Add light grey background
* Remove fade effect from default hover state
* Set link, caption, and credit text to false by default
> Improvements to o-figure 

- packages/larva-patterns/components/c-button/c-button.prototype.js
- packages/larva-patterns/objects/o-email-capture-form/o-email-capture-form.prototype.js
- packages/larva-patterns/objects/o-email-capture-form/o-email-capture-form.twig
- packages/larva-patterns/objects/o-figure/o-figure.prototype.js
- packages/larva-patterns/objects/o-figure/o-figure.twig
* o-figure: Move screen reader text inside figure tag
* c-button, o-email-capture-form: Export default values
* Replace some Object.assigns with clonedeep
> Pattern default fixes

- package-lock.json
- package.json
- packages/larva-patterns/_templates/pattern-nav.html
- packages/larva-patterns/components/c-heading/README.md
- packages/larva-patterns/components/c-lazy-image/README.md
- packages/larva-patterns/objects/o-figure/README.md
- packages/larva-patterns/objects/o-icon-button/README.md
- packages/larva-patterns/objects/o-nav/README.md
- packages/larva-patterns/pattern.html
- packages/larva/lib/server.js
- packages/larva/package.json
Yay!
* Add Twing filter for Markdown
* Inline README content in pattern.html
> Larva UI: Render README in Twig

- packages/larva-patterns/components/c-heading/README.md
- packages/larva-patterns/components/c-heading/c-heading.prototype.js
- packages/larva-patterns/components/c-heading/c-heading.twig
Merge this first: https://github.com/penske-media-corp/pmc-larva/pull/96
> Updates to c-heading naming

- packages/larva-patterns/_templates/pattern-nav.html
- packages/larva-patterns/components/c-button/c-button.prototype.js
- packages/larva-patterns/components/c-button/c-button.twig
- packages/larva-patterns/components/c-link/README.md
- packages/larva/lib/server.js
* Add rel to c-button
* Add c-link readme
* Send all query strings from express to template data
> Small, misc fixes

- packages/larva-js/src/interface/EmailCapture/EmailCapture.js
- packages/larva-js/src/utils/ajaxIconSprite.js
- packages/larva-patterns/objects/o-email-capture-form/o-email-capture-form.twig
* Remove extra ids
* Add encoding for email value
> Email Capture Tweaks

- packages/larva/package.json
- packages/larva/scripts/config/gulpfile.js
The css nano minification stopped working (or maybe never worked...), this gets it working again.
> Fix `prod-css` Gulp task

- now.json
https://zeit.co/docs/configuration#git-integrations/github-enabled
> chore: disable now integration... for now

- CHANGELOG.md
- packages/larva-patterns/modules/post-content-image/post-content-image.prototype.js
- packages/larva-patterns/modules/post-content-image/post-content-image.twig
Manually updating the changelog for now.
> Add post-content-image module & CHANGELOG.md

- CHANGELOG.md
- packages/larva-tokens/build/artinamerica.custom-properties.css
- packages/larva-tokens/build/artinamerica.map.scss
- packages/larva-tokens/build/artnews.custom-properties.css
- packages/larva-tokens/build/artnews.map.scss
- packages/larva-tokens/build/deadline.custom-properties.css
- packages/larva-tokens/build/deadline.map.scss
- packages/larva-tokens/build/default.custom-properties.css
- packages/larva-tokens/build/default.map.scss
- packages/larva-tokens/build/variety-vip.custom-properties.css
- packages/larva-tokens/build/variety-vip.map.scss
- packages/larva-tokens/build/variety.custom-properties.css
- packages/larva-tokens/build/variety.map.scss
- packages/larva-tokens/build/wwd.custom-properties.css
- packages/larva-tokens/build/wwd.map.scss
- packages/larva-tokens/src/base/aliases.json
- packages/larva-tokens/src/base/background-color.json
- packages/larva-tokens/src/base/border-color.json
- packages/larva-tokens/src/base/color.json
- packages/larva-tokens/src/brands/wwd.json
- packages/larva-tokens/style-guides/artinamerica.html
- packages/larva-tokens/style-guides/artnews.html
- packages/larva-tokens/style-guides/deadline.html
- packages/larva-tokens/style-guides/default.html
- packages/larva-tokens/style-guides/variety.html
- packages/larva-tokens/style-guides/wwd.html
- wwd.json was missing some important color definitions (background secondary, border, etc)
- also updated the default colors for background, border, and colors.json to be PMC themed colors
> Update WWD and Default colors in larva-tokens

- packages/larva-tokens/build/sheknows.custom-properties.css
- packages/larva-tokens/build/sheknows.map.scss
- packages/larva-tokens/src/brands/sheknows.json
- packages/larva-tokens/style-guides/sheknows.html
Project style guide: https://projects.invisionapp.com/d/main/default/#/console/15560065/408310283/preview
The style guide in the `pmc-sheknows-2020` theme is working as expected at http://localhost:3000/project/__tests__/style-guide/ after setting up an `npm link` to the `larva-tokens` package and adjusting the `@import`s where noted in a few SCSS files (and the `map-merge` in the scss/00-tools/tokens.scss` file).
Some quick notes:
* We know the web fonts aren't working, so we welcome direction on how to get those properly set up!
* We haven't used aliases for the colors or the fonts - please let us know if that is the preferable approach.
> Add SheKnows design tokens

- packages/backstopjs-config/index.js
Hi! Enjoying learning Larva and want to help where I can :)
Closes issue #178
> Update backstop config for XL Desktop screen size

- CHANGELOG.md
- packages/larva-tokens/build/indiewire.custom-properties.css
- packages/larva-tokens/build/indiewire.map.scss
- packages/larva-tokens/src/brands/indiewire.json
- packages/larva-tokens/style-guides/indiewire.html
Hi @laras126 👋 Here’s a first attempt at some new design tokens for indiewire.
It feels like it may need more work? Here are questions that come to mind…
1. Is it okay to add new fonts like `Argent` to `indiewire.json`? (Should they live in `aliases.json` instead?)
2. Should color tokens be included in `indiewire.json`? (Should this PR wait until those have been worked out?)
3. The style guide mentioned two different body fonts: `Georgia` and `Helvetica Neue`. What would be the best way to express this in `indiewire.json`? I see there’s a `FONT_FAMILY_BODY` and a `FONT_FAMILY_BASIC` in the example template, so I started out by using those.
> Add indiewire design tokens

- CHANGELOG.md
- packages/larva-patterns/modules/button/button.prototype.js
- packages/larva-patterns/modules/button/button.twig
- packages/larva-patterns/modules/paragraph/paragraph.prototype.js
- packages/larva-patterns/modules/paragraph/paragraph.twig
- packages/larva-patterns/modules/separator/separator.prototype.js
- packages/larva-patterns/modules/separator/separator.twig
Hi @laras126 👋
Here’s my first attempt at adding `button` and `separator` modules. To make them more reusable, I tried to keep the class names simple. And I didn’t include any variants.
Hope I got that right! If not, I’ll try again   :o)
> [GUT-57] [GUT-63] feat: button, paragraph and separator modules

- CHANGELOG.md
- packages/larva-patterns/modules/list/list.ordered.js
- packages/larva-patterns/modules/list/list.prototype.js
- packages/larva-patterns/modules/list/list.twig
Using a similiar style as headers to have multiple html elements in one pattern
> add list module

- packages/larva/package.json
> Correct larva package eslint dependency

- CHANGELOG.md
- packages/larva-patterns/components/c-link/c-link.prototype.js
- packages/larva-patterns/components/c-link/c-link.twig
- Add the aria-label attribute to c-link component.
> Add aria-label attribute to c-link component

- packages/larva-js/src/interface/MegaMenu/MegaMenu.js
Ticket: https://jira.pmcdev.io/browse/PMCP-2796
> PMCP-2796: Add focus trap to mega menu modal

- PULL_REQUEST_TEMPLATE.md
Until we have automation to take care of them, add a PR checklist so we don't forget to do things.
> PR Checklist Template

- CHANGELOG.md
- packages/larva-patterns/modules/newsletter-cta/newsletter-cta.prototype.js
- packages/larva-patterns/modules/newsletter-cta/newsletter-cta.twig
> Add newsletter-cta module

- CHANGELOG.md
- packages/larva-patterns/modules/vlanding-video-showcase/vlanding-video-showcase.twig
- packages/larva-patterns/package-lock.json
Add conditions so this does not cause a fatal error if some data is not available or used.
> Add conditions for video showcase

- CHANGELOG.md
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-button.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-byline.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-heading.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-logo.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-nav-link.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/modules/array-key-in-loop.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/modules/breadcrumbs.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/modules/html-tag-interpolation.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/modules/trending.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/objects/o-crap.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/objects/o-nav.php
- packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/objects/o-story-list.php
- packages/twig-to-php-parser/lib/twig-to-php-parser.php
> Adding correct format to filedoc generated in twig parser.

- CHANGELOG.md
> Changelog update for 0.6.1

- CHANGELOG.md
> PMCP-3799: Changelog fix

- CHANGELOG.md
> Updating Changelog for release

- CHANGELOG.md
> Updating Changelog.md for release

- packages/larva-patterns/components/c-figcaption/c-figcaption.twig
- Updates to c-figcaption pattern with `c_figcaption_credit_text_markup` field which will have `wp_kses_post()` as sanitization wrapper to support html markup.
- This change is added by keeping backward compatibility in mind.
JIRA ticket: https://jira.pmcdev.io/browse/PMCP-3744
> PMCP-3744 : Featured Article - Add Featured Media text overlay tool

- package-lock.json
- package.json
Locks Node version to 14 to fix issues with build in later versions.
> Lock node version to 14

- CHANGELOG.md
> PR for release

- CHANGELOG.md
> PMCP-4286 : Pullquote Block - Feature Style

- CHANGELOG.md
> Update changelog release version

- CHANGELOG.md
> Add 1.43.0 changes

- packages/eslint-config/package-lock.json
- packages/eslint-config/package.json
in preparation for Node 18
For [PASE-1798](https://penskemedia.atlassian.net/browse/PASE-1798)
> Update eslint-config's @wordpress/eslint-plugin dependency

- CHANGELOG.md
- package-lock.json
- package.json
Publishing an [alpha version](https://www.npmjs.com/package/@penskemediacorp/larva/v/1.60.1-alpha.0) worked, but unfortunately we're still experiencing the same issues with `npx lerna publish`.
> Upgrade Lerna to V8
