packages/larva-patterns/components/c-button/c-button.brand-basic.js, packages/larva-patterns/components/c-button/c-button.ghost.js, packages/larva-patterns/components/c-email-field/c-email-field.ghost.js, packages/larva-patterns/objects/o-email-capture-form/o-email-capture-form.prototype.js, packages/larva-patterns/objects/o-nav/o-nav.horizontal.js
* Remove a font family class
* Add `brand-basic` c-button variation
* Remove `.clone` method for a few patterns – no longer using that so that text editors can read the actual module and provide hints
* Also remove hard coded `c-email-field` obj from `o-email-capture-form`
=> Pattern fixes

packages/twig-to-php-parser/__tests__/fixtures/src/patterns/04-components/c-logo/c-logo.twig, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-logo.php, packages/twig-to-php-parser/__tests__/twig-to-php-parser.test.js, packages/twig-to-php-parser/lib/twig-to-php-parser.php
This is a cool one! Trim off the `|filter` from a variable name, so we can use Twig filters in pattern templates to help with demo content.
=> Support Twig Filters in Parser

packages/larva-scss/dist/_tokens.scss, packages/larva-scss/lib/tokens/_shadows.scss
Note these are "unofficial" tokens as map-less Sass variables – eventually they can be added to larva-tokens. For now, this will be fine.
=> Enable shadow tokens

packages/larva-patterns/objects/o-icon-button/README.md, packages/larva-patterns/objects/o-icon-button/o-icon-button.prototype.js, packages/larva-patterns/objects/o-icon-button/o-icon-button.search.js, packages/larva-patterns/package.json
- Add `o-icon-button.search`
- Add lodash.clonedeep to deep clone pattern objects – eventually will need to refactor existing patterns to include this and other, future helper methods, but for now, this will be used as needed.
=> o-icon-button: Search configuration

packages/larva-patterns/objects/o-tease-list/o-tease-list.prototype.js, packages/larva-patterns/objects/o-tease/o-tease.prototype.js, packages/larva-patterns/objects/o-tease/o-tease.twig
Merge https://github.com/penske-media-corp/pmc-larva/tree/fix/o-figure first.
This PR updates o-tease and o-tease-list schemas to use c-lazy-image.
=> [o-tease] refact: use c-lazy-image in o-tease

packages/larva-css/build/css/generic.common.inline.css, packages/larva-css/src/01-generic/elements.common.inline.scss, packages/larva-patterns/components/c-figcaption/c-figcaption.prototype.js, packages/larva-patterns/components/c-figcaption/c-figcaption.twig, packages/larva-patterns/components/c-heading/c-heading.prototype.js, packages/larva-patterns/components/c-lazy-image/c-lazy-image.prototype.js, packages/larva-patterns/components/c-lazy-image/c-lazy-image.twig, packages/larva-patterns/objects/o-figure/o-figure.prototype.js, packages/larva-patterns/objects/o-figure/o-figure.twig, packages/larva-patterns/objects/o-header/o-header.prototype.js, packages/larva-patterns/objects/o-header/o-header.twig, packages/larva-patterns/objects/o-sponsored-by/o-sponsored-by.prototype.js, packages/larva-patterns/objects/o-sponsored-by/o-sponsored-by.twig, packages/larva-patterns/objects/o-tease-list/o-tease-list.prototype.js, packages/larva-patterns/objects/o-tease/o-tease.prototype.js, packages/larva-patterns/objects/o-tease/o-tease.twig, packages/larva/__tests__/lib/utils/getPatternData.test.js, packages/larva/lib/utils/getPatternData.js, packages/larva/lib/utils/getPatternDataPath.js
Break up o-figure into smaller components:
* c-lazy-image
* c-figcaption
General improvements to o-figure:
* Remove c-button, it's not being used anywhere and that should be the responsibility of a module
* Remove option for screen reader text - o-figure should be used with a caption and credit
* Move crop class and inline crop to same tag in c-lazy-image
=> o-figure: Refactor and split into components

packages/larva-patterns/_templates/pattern-nav.html, packages/larva-patterns/algorithms/a-icon/a-icon.html, packages/larva-patterns/pattern.html, packages/larva/lib/server.js
* Update terms in accordians to match glossary
* Add one-offs to pattern nav
Note: CSS Algorithms demo markup should be treated as a one-off at project level. A separate docs area for CSS algos and utils is in the future.
=> Docs + Larva UI work

packages/backstopjs-config/README.md, packages/backstopjs-config/__tests__/backstopjs-config.test.js, packages/backstopjs-config/index.js, packages/backstopjs-config/lib/getScenarios.js
Fix an issue where with QA URL testing the selector override only applied to the first scenario.
=> PMCP-1671: Backstop Bugfix

packages/twig-to-php-parser/__tests__/parser-methods.test.js, packages/twig-to-php-parser/lib/twig-to-php-parser.php
Dependent on an update to pmc-core-v2 that adds all templates from Larva.
=> Enable parent theme logic in parser

packages/larva-patterns/components/c-link/c-link.prototype.js, packages/larva-patterns/components/c-link/c-link.twig
I've extended this component to support toggling a feature on (c_link_is_external) in order to add the target & rel noopener attributes to it. 
The noopener is added as per the following (and to avoid the related security concerns when not having this rel attribute present)
https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/
=> Add support for target=“_blank” on the link component

CHANGELOG.md, packages/twig-to-php-parser/README.md, packages/twig-to-php-parser/__tests__/fixtures/larva.config.js, packages/twig-to-php-parser/__tests__/parser-methods.test.js, packages/twig-to-php-parser/__tests__/twig-to-php-parser.test.js, packages/twig-to-php-parser/index.js, packages/twig-to-php-parser/lib/twig-to-php-parser.php
This `twig-to-php-parser` package is pretty smelly. In a future Larva chat, we can discuss moving this to the pmc-larva plugin and handle the configuration there, or another approach to clean up how config is handled in this mono-repo. Or not.
Changes included here in this PR are noted in the changelog.
=> GUT-46: Update parser to support template paths from plugin 

CHANGELOG.md, packages/twig-to-php-parser/__tests__/parser-methods.test.js, packages/twig-to-php-parser/lib/twig-to-php-parser.php
Since we will not have other template parts in the pmc-plugins/pmc-larva repo, the built patterns can be stored in the build/ directory.
This will also discourage the addition of any controller code to the plugin. That should live in the theme or another plugin.
=> [GUT-45] fix: update include path for plugin

CHANGELOG.md, packages/twig-to-php-parser/__tests__/parser-methods.test.js, packages/twig-to-php-parser/lib/twig-to-php-parser.php
Update to use the `Pattern::render_pattern_template` method in the parser for themes using the pmc-plugin - only Indiewire.
=> Update parser to new plugin method

CHANGELOG.md, packages/larva/lib/server.js
We only need the one to projectPatternsDir - not to larvaPatternsDir.
=> Remove static assets route for larvaPatternsDir

CHANGELOG.md, packages/larva-patterns/objects/o-nav/o-nav.twig
Fix: Accessibility issues: Broken ARIA reference by adding condition check before adding an empty aria-labelledby attribute to o-nav.
=> Fix: Accessibility issues: Broken ARIA reference

packages/site/src/components/TokenListItem.js, packages/site/src/components/TokensView.js, packages/site/src/data.js
In order to manage the values of default tokens in one place, the tokens form should only copy the token values that have changed.
To check this functionality:
1. Navigate to the branch deployment here: https://pmc-larva-git-fix-tokens-diff-penske-media-corp.vercel.app
2. Select "Design Tokens"
2. Create tokens for a new brand with any name.
3. Change the value of any token on the right
4. Click "Save JSON to file". 
5. In the file, ensure there is only one token in the "props" key.
=> Tokens Form: Only copy token values that are changed from default

CHANGELOG.md, packages/larva-patterns/objects/o-social-list/o-social-list.twig
=> PMCP-3027: Allow o-icon-button to be used in o-social-list

CHANGELOG.md, packages/larva-patterns/modules/story/story.twig
Story Block Engine allows dek to be hidden, in which case the `c_dek` data node is set to `false`. Currently, this produces a fatal error due to the missing check.
=> Update Larva pattern to match block's options

CHANGELOG.md, packages/larva-patterns/modules/separator/separator.thick.js, packages/larva-patterns/modules/separator/separator.wide-thick.js, packages/larva-patterns/modules/separator/separator.wide.js
Introduces thicker separator variants, as well as porting the `wide` variant from IndieWire.
=> Add separator variants

CHANGELOG.md
=> Chore: changelog

CHANGELOG.md, packages/larva-patterns/__tests__/hub/hub.html, packages/larva-patterns/__tests__/hub/hub.prototype.js, packages/larva/lib/generateStatic.js, packages/larva/lib/server.js, packages/larva/lib/utils/getAppConfiguration.js, packages/larva/scripts/build-html.js
Add configuration to support copying local webfont files to the /assets/public so that they work on the static sites.
Corresponding documentation here: https://confluence.pmcdev.io/x/JQqeAw
Example static style guide with working local webfonts here: https://robbreport.stg.larva.pmcdev.io/larva/style-guide/
Additionally, add a static version of the hub modules for quick visibility and future regression testing: https://pmc-larva-ncscbugnd-penske-media-corp.vercel.app/larva/__tests__/hub/
Pre-release # (or n/a): 0.3.9-develop.3+7ba1cc94 tested on RobbReport theme.
- - [x] If changes to Larva server: Static site generates as expected in a theme  (avail. on a URL {brand}.stg.larva.pmcdev.io)
=> GUT-106: Copy webfonts from theme when building static site

CHANGELOG.md, packages/larva/scripts/init.js
Add script command for _update-larva_ to list of commands in init log message.
=> Add update-larva script to init log

CHANGELOG.md
Update CHANGELOG for 0.5.2 release.
=> Updates changelog for 0.5.2 release

CHANGELOG.md
Updates the changelog to reflect the `0.5.7` release.
- [o] `npm run prod` in this repo outputs expected changes (excepting the issue with re-ordered partials in larva-css algorithms partials - see [LRVA-1885](https://jira.pmcdev.io/browse/LRVA-1885))
- [o] If adding a new pattern, in the PR comment, included a screenshot and link to the static Vercel deployment
- [o] If changes to build scripts or the Node.js server, tested changes in pmc-spark [via a pre-release](https://confluence.pmcdev.io/x/XhOeAw)
=> Update changelog for `0.5.7` release

CHANGELOG.md, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-button.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-byline.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-heading.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-logo.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/components/c-nav-link.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/modules/array-key-in-loop.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/modules/breadcrumbs.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/modules/html-tag-interpolation.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/modules/trending.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/objects/o-crap.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/objects/o-nav.php, packages/twig-to-php-parser/__tests__/fixtures/template-parts-expected/patterns/objects/o-story-list.php, packages/twig-to-php-parser/lib/twig-to-php-parser.php
Modified the structure of generated comments to adhere to filedoc standard.
=> Changing the structure of generated php comments in the twig parser.

CHANGELOG.md
=> moves unpublished comments to new version, changelog

CHANGELOG.md
=> Updating changelog for 1.7.1 release

CHANGELOG.md, packages/larva-patterns/components/c-lazy-image/c-lazy-image.prototype.js, packages/larva-patterns/components/c-lazy-image/c-lazy-image.twig
Add image decoding attribute support.
=> Add image decoding attribute support

packages/larva-js/package-lock.json, packages/larva-tokens/package-lock.json
Dependabot opened a few pull requests to bump terser and moment in our repo; this did it manuallly.
=> Run npm audit

CHANGELOG.md
=> Preparing for the Larva release v1.31.0

CHANGELOG.md, packages/larva-patterns/components/c-title/c-title.twig
=> Add c-title link target attr

CHANGELOG.md, packages/larva-patterns/modules/page-404/page-404.prototype.js, packages/larva-patterns/modules/page-404/page-404.smart.js, packages/larva-patterns/modules/page-404/page-404.twig
Summary
---
This PR, when enabled,
- Adds smart prototype for `page-404` module.
[Previous PR](https://github.com/penske-media-corp/pmc-larva/pull/788) to `page-404` module has replaced buttons with suggested links. Now the need has changed to roll out Smart 404 incrementally across brands, so it requires both prototypes (with buttons and with suggested links) to run simultaneously. Hence we are adding Suggested Links as a separate prototype to run both versions side-by-side.
Issue url or additional context
---
https://penskemedia.atlassian.net/browse/1408
=> [PASE-1408] SEO: CORE TECH - Roll out Smart 404 to ARTnews, Sportico, Dirt

.github/workflows/vercel.yml, vercel.json
Switches Vercel deploys to a GitHub action
=> Add Vercel workflow

CHANGELOG.md, packages/larva/scripts/config/webpack.config.js
=> Switch Webpack config "query" JS rule that's throwing warnings and build errors out for "options"

CHANGELOG.md, packages/twig-to-php-parser/index.js
Removed a `console.log()` from `twig-to-php-parser` that was recently added for testing/troubleshooting.
=> Remove twig parser `console.log` for prior testing

CHANGELOG.md, packages/larva-patterns/modules/heading/heading.twig
=> adds anchor id support for heading

CHANGELOG.md, packages/larva-patterns/modules/pullquote/pullquote.memo.js
This change adds the pullquote.memo prototype that is referenced by some brands.
Ticket: https://penskemedia.atlassian.net/browse/BR-3030
=> BR-3030: Add pullquote memo prototype.

CHANGELOG.md, README.md, packages/larva-patterns/modules/article-kicker/article-kicker.prototype.js, packages/larva-patterns/modules/article-kicker/article-kicker.twig
larva-patterns - Adds new kicker image support to the article kicker module.
=> larva-patterns - Adds new kicker image support to the article kicker module.

CHANGELOG.md, packages/larva-patterns/components/c-button/c-button.twig
Add aria-label attribute for c-button component
=> CORP-620: Add aria-label attribute for c-button component
